name: Deploy images


on:
  push:
     branches: 
       - master  

jobs:
  deploy-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Build and Push Docker Image
        run: docker build -t ghcr.io/timoj58/blackjack-go-app:latest blackjack-go-app/
      - run: docker push ghcr.io/timoj58/blackjack-go-app:latest

  deploy-react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build locally 
        run: npm install --prefix blackjack-react-app/ 
      - run: npm run build --prefix blackjack-react-app/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Build and Push Docker Image
        run: docker build -t ghcr.io/timoj58/blackjack-react-app:latest blackjack-react-app/
      - run: docker push ghcr.io/timoj58/blackjack-react-app:latest

